/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedResellerRouteImport } from './routes/_authenticated.reseller'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedResellerIndexRouteImport } from './routes/_authenticated.reseller.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedResellerTokensRouteImport } from './routes/_authenticated.reseller.tokens'
import { Route as AuthenticatedResellerLicensesRouteImport } from './routes/_authenticated.reseller.licenses'
import { Route as AuthenticatedResellerGenerateRouteImport } from './routes/_authenticated.reseller.generate'
import { Route as AuthenticatedAdminVersionsRouteImport } from './routes/_authenticated.admin.versions'
import { Route as AuthenticatedAdminTokensRouteImport } from './routes/_authenticated.admin.tokens'
import { Route as AuthenticatedAdminResellersRouteImport } from './routes/_authenticated.admin.resellers'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated.admin.notifications'
import { Route as AuthenticatedAdminLicensesRouteImport } from './routes/_authenticated.admin.licenses'
import { Route as AuthenticatedAdminCreateLicenseRouteImport } from './routes/_authenticated.admin.create-license'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated.admin.approvals'

const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResellerRoute = AuthenticatedResellerRouteImport.update({
  id: '/reseller',
  path: '/reseller',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResellerIndexRoute =
  AuthenticatedResellerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedResellerRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedResellerTokensRoute =
  AuthenticatedResellerTokensRouteImport.update({
    id: '/tokens',
    path: '/tokens',
    getParentRoute: () => AuthenticatedResellerRoute,
  } as any)
const AuthenticatedResellerLicensesRoute =
  AuthenticatedResellerLicensesRouteImport.update({
    id: '/licenses',
    path: '/licenses',
    getParentRoute: () => AuthenticatedResellerRoute,
  } as any)
const AuthenticatedResellerGenerateRoute =
  AuthenticatedResellerGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => AuthenticatedResellerRoute,
  } as any)
const AuthenticatedAdminVersionsRoute =
  AuthenticatedAdminVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTokensRoute =
  AuthenticatedAdminTokensRouteImport.update({
    id: '/tokens',
    path: '/tokens',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResellersRoute =
  AuthenticatedAdminResellersRouteImport.update({
    id: '/resellers',
    path: '/resellers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLicensesRoute =
  AuthenticatedAdminLicensesRouteImport.update({
    id: '/licenses',
    path: '/licenses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCreateLicenseRoute =
  AuthenticatedAdminCreateLicenseRouteImport.update({
    id: '/create-license',
    path: '/create-license',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/reseller': typeof AuthenticatedResellerRouteWithChildren
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/create-license': typeof AuthenticatedAdminCreateLicenseRoute
  '/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/resellers': typeof AuthenticatedAdminResellersRoute
  '/admin/tokens': typeof AuthenticatedAdminTokensRoute
  '/admin/versions': typeof AuthenticatedAdminVersionsRoute
  '/reseller/generate': typeof AuthenticatedResellerGenerateRoute
  '/reseller/licenses': typeof AuthenticatedResellerLicensesRoute
  '/reseller/tokens': typeof AuthenticatedResellerTokensRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/reseller/': typeof AuthenticatedResellerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/create-license': typeof AuthenticatedAdminCreateLicenseRoute
  '/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/resellers': typeof AuthenticatedAdminResellersRoute
  '/admin/tokens': typeof AuthenticatedAdminTokensRoute
  '/admin/versions': typeof AuthenticatedAdminVersionsRoute
  '/reseller/generate': typeof AuthenticatedResellerGenerateRoute
  '/reseller/licenses': typeof AuthenticatedResellerLicensesRoute
  '/reseller/tokens': typeof AuthenticatedResellerTokensRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/reseller': typeof AuthenticatedResellerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/reseller': typeof AuthenticatedResellerRouteWithChildren
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/create-license': typeof AuthenticatedAdminCreateLicenseRoute
  '/_authenticated/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/resellers': typeof AuthenticatedAdminResellersRoute
  '/_authenticated/admin/tokens': typeof AuthenticatedAdminTokensRoute
  '/_authenticated/admin/versions': typeof AuthenticatedAdminVersionsRoute
  '/_authenticated/reseller/generate': typeof AuthenticatedResellerGenerateRoute
  '/_authenticated/reseller/licenses': typeof AuthenticatedResellerLicensesRoute
  '/_authenticated/reseller/tokens': typeof AuthenticatedResellerTokensRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/reseller/': typeof AuthenticatedResellerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending'
    | '/admin'
    | '/reseller'
    | '/admin/approvals'
    | '/admin/create-license'
    | '/admin/licenses'
    | '/admin/notifications'
    | '/admin/resellers'
    | '/admin/tokens'
    | '/admin/versions'
    | '/reseller/generate'
    | '/reseller/licenses'
    | '/reseller/tokens'
    | '/admin/'
    | '/reseller/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pending'
    | '/admin/approvals'
    | '/admin/create-license'
    | '/admin/licenses'
    | '/admin/notifications'
    | '/admin/resellers'
    | '/admin/tokens'
    | '/admin/versions'
    | '/reseller/generate'
    | '/reseller/licenses'
    | '/reseller/tokens'
    | '/admin'
    | '/reseller'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pending'
    | '/_authenticated/admin'
    | '/_authenticated/reseller'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/create-license'
    | '/_authenticated/admin/licenses'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/resellers'
    | '/_authenticated/admin/tokens'
    | '/_authenticated/admin/versions'
    | '/_authenticated/reseller/generate'
    | '/_authenticated/reseller/licenses'
    | '/_authenticated/reseller/tokens'
    | '/_authenticated/admin/'
    | '/_authenticated/reseller/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reseller': {
      id: '/_authenticated/reseller'
      path: '/reseller'
      fullPath: '/reseller'
      preLoaderRoute: typeof AuthenticatedResellerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reseller/': {
      id: '/_authenticated/reseller/'
      path: '/'
      fullPath: '/reseller/'
      preLoaderRoute: typeof AuthenticatedResellerIndexRouteImport
      parentRoute: typeof AuthenticatedResellerRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/reseller/tokens': {
      id: '/_authenticated/reseller/tokens'
      path: '/tokens'
      fullPath: '/reseller/tokens'
      preLoaderRoute: typeof AuthenticatedResellerTokensRouteImport
      parentRoute: typeof AuthenticatedResellerRoute
    }
    '/_authenticated/reseller/licenses': {
      id: '/_authenticated/reseller/licenses'
      path: '/licenses'
      fullPath: '/reseller/licenses'
      preLoaderRoute: typeof AuthenticatedResellerLicensesRouteImport
      parentRoute: typeof AuthenticatedResellerRoute
    }
    '/_authenticated/reseller/generate': {
      id: '/_authenticated/reseller/generate'
      path: '/generate'
      fullPath: '/reseller/generate'
      preLoaderRoute: typeof AuthenticatedResellerGenerateRouteImport
      parentRoute: typeof AuthenticatedResellerRoute
    }
    '/_authenticated/admin/versions': {
      id: '/_authenticated/admin/versions'
      path: '/versions'
      fullPath: '/admin/versions'
      preLoaderRoute: typeof AuthenticatedAdminVersionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tokens': {
      id: '/_authenticated/admin/tokens'
      path: '/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AuthenticatedAdminTokensRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resellers': {
      id: '/_authenticated/admin/resellers'
      path: '/resellers'
      fullPath: '/admin/resellers'
      preLoaderRoute: typeof AuthenticatedAdminResellersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/licenses': {
      id: '/_authenticated/admin/licenses'
      path: '/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AuthenticatedAdminLicensesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/create-license': {
      id: '/_authenticated/admin/create-license'
      path: '/create-license'
      fullPath: '/admin/create-license'
      preLoaderRoute: typeof AuthenticatedAdminCreateLicenseRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminCreateLicenseRoute: typeof AuthenticatedAdminCreateLicenseRoute
  AuthenticatedAdminLicensesRoute: typeof AuthenticatedAdminLicensesRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminResellersRoute: typeof AuthenticatedAdminResellersRoute
  AuthenticatedAdminTokensRoute: typeof AuthenticatedAdminTokensRoute
  AuthenticatedAdminVersionsRoute: typeof AuthenticatedAdminVersionsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
  AuthenticatedAdminCreateLicenseRoute: AuthenticatedAdminCreateLicenseRoute,
  AuthenticatedAdminLicensesRoute: AuthenticatedAdminLicensesRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminResellersRoute: AuthenticatedAdminResellersRoute,
  AuthenticatedAdminTokensRoute: AuthenticatedAdminTokensRoute,
  AuthenticatedAdminVersionsRoute: AuthenticatedAdminVersionsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedResellerRouteChildren {
  AuthenticatedResellerGenerateRoute: typeof AuthenticatedResellerGenerateRoute
  AuthenticatedResellerLicensesRoute: typeof AuthenticatedResellerLicensesRoute
  AuthenticatedResellerTokensRoute: typeof AuthenticatedResellerTokensRoute
  AuthenticatedResellerIndexRoute: typeof AuthenticatedResellerIndexRoute
}

const AuthenticatedResellerRouteChildren: AuthenticatedResellerRouteChildren = {
  AuthenticatedResellerGenerateRoute: AuthenticatedResellerGenerateRoute,
  AuthenticatedResellerLicensesRoute: AuthenticatedResellerLicensesRoute,
  AuthenticatedResellerTokensRoute: AuthenticatedResellerTokensRoute,
  AuthenticatedResellerIndexRoute: AuthenticatedResellerIndexRoute,
}

const AuthenticatedResellerRouteWithChildren =
  AuthenticatedResellerRoute._addFileChildren(
    AuthenticatedResellerRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedResellerRoute: typeof AuthenticatedResellerRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedResellerRoute: AuthenticatedResellerRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
